apiVersion: v1
kind: Service
metadata:
  name: newyo-service
  namespace: test
spec:
  selector:
    app: newyo
  ports:
    - protocol: TCP
      port: 30100
      targetPort: 30100
      nodePort: 30100
  type: NodePort
